apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: php-fpm
          image: "alexdpy/lolilol:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
          - containerPort: 9000
          env:
            - name: APP_ENV
              value: prod
            - name: APP_SECRET
              value: 5c7828c4eaa35d2665366d281acb2793
        - name: nginx
          image: "nginx:stable"
          imagePullPolicy: IfNotPresent
          volumeMounts:
           - name: nginx-config
             mountPath: /etc/nginx/conf.d
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config